# Generated by Django 3.0.2 on 2020-01-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplied',
            name='job_id',
            field=models.IntegerField(default=0),
        ),
    ]
